## **Introduction to Colab and Python**

Welcome to this introductory Google Colab Notebook. Colab is a Python development environment that runs in the browser using Google Cloud. A notebook is a platform where you can mix explanatory text and code in different cells. This setup is quite useful for programming tutorials. This notebook is a quick introduction to the Python programming language and the environment. 
You can play around various Python language syntax. Feel free to edit the code to develop a deeper understanding. If you have further questions or run into troubles while editing the code, you are highly encouraged to search further information using Google search engine. 

**Credits:** This Notebook is heavily inspired from the Notebook by Google staff https://github.com/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l01c01_introduction_to_colab_and_python.ipynb

# Hello Python in Google Colab World

Let's greet the Python and Google Colab world using the simplest Python code shown below. To run this code just hover the mouse over [ ] and press the play button to the upper left. Or press shift-enter to execute.

Since this is the first piece of code in this notebook, it will take a few seconds to execute. During this time, Colab allocates some CPU/GPU/RAM resources on its cloud computing platform. Once done, you can see these resources on the top right corner (RAM/Disk). 

In [2]:
print("Hello Python in Google Colab World")

Hello Python in Google Colab World


## Functions, Conditional Statements and Loops/Iterations
Let's create a Python function, and call it from a loop.

In [3]:
def HelloWorldXY(x, y):
  if (x < 10):
    print("{} is less than 10".format(x))
  elif (x < 20):
    print("{} is less than 20 but more than or equal to 10".format(x))
  else:
    print("{} is more than or equal to 20".format(x))
  return x + y

for i in range(8, 25, 5):  # i=8, 13, 18, 23 (start, stop, step)
  print("Iteration # {}".format(i))
  r = HelloWorldXY(i,i*2)
  print("{}+{}={}".format(i,i*2,r))

Iteration # 8
8 is less than 10
8+16=24
Iteration # 13
13 is less than 20 but more than or equal to 10
13+26=39
Iteration # 18
18 is less than 20 but more than or equal to 10
18+36=54
Iteration # 23
23 is more than or equal to 20
23+46=69


In [4]:
print(HelloWorldXY(1,2))

1 is less than 10
3


In most computer languages, array indexing starts at 0 (Matlab excluded). Thus, in order to access individual members of an array you have to iterate (loop) starting at 0 all the way to 'N-1' where N is the size of the array.

In [5]:
print("Iterate over the members of an array/list of size 5")
N = 5
for i in range(N):
  print(i)

print("Iterate using explicit index")
for i in [0,1,2,3,4]:
  print(i)

print("Iterate using while loop")
i = 0
while i < N:
  print(i)
  i += 1

Iterate over the members of an array/list of size 5
0
1
2
3
4
Iterate using explicit index
0
1
2
3
4
Iterate using while loop
0
1
2
3
4


In [6]:
print("Python supports standard key words like continue and break")
while True:
  print("Entered while")
  break

Python supports standard key words like continue and break
Entered while


## Numpy and lists
Python has lists built into the language.
However, a library called Numpy can be used as well for this purpose.
Numpy gives you lots of support functions that are useful when doing Machine Learning.

Numpy libaray is "imported" using an import statement. This statement makes the entire numpy package available and we can access those symbols using the abbreviated 'np' syntax.

In [7]:
import numpy as np  # Make numpy available using np.

# Create a numpy character/text array, and append an element
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element one by one")
for i in a:
  print(i)

print("\nPrinting each element and their index")
for i,e in enumerate(a):
  print("Index: {}, was: {}".format(i, e))

Current array: ['Hello' 'World' '!']
Printing each element one by one
Hello
World
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


In [8]:
print("\nLet's do some basic maths on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


Let's do some basic maths on arrays
Max: 4
Average: 2.0
Max index: 2


In [9]:
print("\nYou can print the data type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0])))


You can print the data type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int32'>


In [10]:
print("\nUse numpy to create a [3,3] dimension array with random numbers")
c = np.random.rand(3, 3)
print(c)


Use numpy to create a [3,3] dimension array with random numbers
[[0.51341429 0.42692127 0.76303665]
 [0.30398885 0.25358771 0.83048788]
 [0.17616591 0.07134192 0.71883389]]


In [11]:
print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))
print("...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists")


You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)
...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists


## Colab Specifics

Colab is a virtual machine you can access directly. To run commands at the VM's terminal, prefix the line with an exclamation point (!).


In [ ]:
print("\nDoing $ls on filesystem")
!ls -l
!pwd

In [ ]:
print("Install numpy")  # Just for test, numpy is actually preinstalled in all Colab instances
!pip install numpy